services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 4173:4173

    networks:
      - internal

    volumes:
      - ./.env:/app/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4173:4173"
    depends_on:
      - vite-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
