services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 80:4173

    networks:
      - internal

    volumes:
      - ./.env:/app/.env

networks:
  internal:

volumes:
  data:
