services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 4173:4173

    networks:
      - internal

    volumes:
      - ./.env:/app/.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80 # Expose HTTP
      - 443:443 # Expose HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx configuration
      - /etc/letsencrypt:/etc/letsencrypt # For SSL certificates
    networks:
      - internal
    depends_on:
      - frontend

networks:
  internal:

volumes:
  data:
