version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - internal
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production # or other environment variables if needed
    depends_on:
      - backend # (Optional if you have a backend service)
    restart: always # Optional: restart container on failure

networks:
  internal:

volumes:
  data:
