name: Deploy to IONOS Cloud Server

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to IONOS
        env:
          IONOS_USER: ${{ secrets.IONOS_USER }} # Your IONOS username
          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }} # Your IONOS password
          IONOS_SERVER_IP: ${{ secrets.IONOS_SERVER_IP }} # Your IONOS server IP address
        run: |
          # Install SSH client if not available
          sudo apt-get install -y openssh-client

          # Copy the built files to the IONOS server
          scp -r build/* $IONOS_USER@$IONOS_SERVER_IP:/app
