name: Deploy to IONOS Cloud Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to IONOS using Docker Compose
        env:
          IONOS_USER: ${{ secrets.IONOS_USER }} # IONOS username
          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }} # IONOS password
          IONOS_SERVER_IP: ${{ secrets.IONOS_SERVER_IP }} # IONOS server IP address
        run: |
          sshpass -p $IONOS_PASSWORD ssh -o StrictHostKeyChecking=no $IONOS_USER@$IONOS_SERVER_IP "cd /letphil-site docker-compose pull && docker-compose up -d"
